### ISSUE TITLE
H.264 more slaggish and blurry than RFX on VMs without dedicated GPU

### ISSUE THREAD

**Issue by JakkuSakura** [neutrinolabs/xrdp#3489]
### xrdp version

0.10.2

### Detailed xrdp version, build options

~~~
xrdp --version
xrdp 0.10.2
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2024 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --prefix=/usr
      --sysconfdir=/etc
      --libexecdir=/usr/lib
      --localstatedir=/var
      --sbindir=/usr/bin
      --with-systemdsystemunitdir=/usr/lib/systemd/system
      --enable-jpeg
      --enable-tjpeg
      --enable-fuse
      --enable-fdkaac
      --enable-opus
      --enable-rfxcodec
      --enable-mp3lame
      --enable-pixman
      --enable-painter
      --enable-vsock
      --enable-ipv6
      --enable-pam-config=arch
      --enable-rdpsndaudin
      --with-imlib2
      --enable-x264
      CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection         -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -flto=auto
      LDFLAGS=-Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now          -Wl,-z,pack-relative-relocs -flto=auto
      CXXFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection         -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wp,-D_GLIBCXX_ASSERTIONS -flto=auto

  Compiled with OpenSSL 3.4.1 11 Feb 2025
~~~

### Operating system & version

Manjaro Linux

### Installation method

other

### Which backend do you use?

xorg

### What desktop environment do you use?

KDE

### Environment xrdp running on

Inside a VM without graphics ccard

### What's your client?

Windows Aps from MacOS AppStore

### Area(s) with issue?

Performance

### Steps to reproduce

I'm mainly using xrdp for my home office setup. I usually connect to multiple VMs via MacOS Windows Apps. I did iperf3 and it shows I have 5Gbps ethernet connection, so performance is not an issue. I have an Ubuntu VM that installed `0.10.1`, which has only RFX support. It runs snappily fast, and I can even watch YouTube over RDP. However, with my Manjaro VM, xrdp `0.10.2` defaults to H264 codec and it's blurry, sluggish. I tried multiple configurations, but none works as good as good old RFX.

This might not be a bug, but good to be posted here to let people be aware of this issue

### Anything else?

cat /etc/xrdp/gfx.toml
```toml
[codec]
# order = [ "H.264", "RFX" ]
# I tested out, RFX is better than H264
order = ["RFX", "H.264"]

# Specify a preferred H.264 encoder, "x264" or "OpenH264".
# This parameter takes effect only when more than one encoder is
# enabled at compile time. If only one encoder is enabled, the encoder
# will be used regardless the value of this parameter.
h264_encoder = "x264"

#
# Configurations for x264
#
[x264.default]
# NOTE: x264 specifies bitrate in unit of kbps.
preset = "ultrafast"
tune = "zerolatency"
profile = "main"     # profile is forced to baseline if preset == ultrafast
vbv_max_bitrate = 0
vbv_buffer_size = 0
fps_num = 60
fps_den = 1

[x264.lan]
preset = "slow" # I tried medium, untrafast, and slow. They made a difference in video quality, but still slaggy and laggy when I watch video.


[x264.wan]
vbv_max_bitrate = 15_000
vbv_buffer_size = 1_500

[x264.broadband_high]
preset = "superfast"
vbv_max_bitrate = 8_000
vbv_buffer_Size = 800

[x264.satellite]
preset = "superfast"
vbv_max_bitrate = 5_000
vbv_buffer_size = 500

[x264.broadband_low]
preset = "veryfast"
vbv_max_bitrate = 1_600
vbv_buffer_size = 66

[x264.modem]
preset = "fast"
vbv_max_bitrate = 1_200
vbv_buffer_size = 50

#
# Configurations for OpenH264
#
[OpenH264.default]
# NOTE: OpenH264 specifies bitrate in unit of bps, not kbps.
EnableFrameSkip = false
TargetBitrate = 20_000_000
MaxBitrate =    0          # unspecified
MaxFrameRate = 60.0

[OpenH264.lan]
# inherits default

[OpenH264.wan]
TargetBitrate = 10_000_000
MaxBitrate =    12_000_000

[OpenH264.broadband_high]
EnableFrameSkip = true
TargetBitrate = 8_000_000
MaxBitrate =   10_000_000

[OpenH264.satellite]
EnableFrameSkip = true
TargetBitrate = 4_000_000
MaxBitrate =    6_000_000

[OpenH264.broadband_low]
EnableFrameSkip = true
TargetBitrate = 1_600_000
MaxBitrate =    1_800_000

[OpenH264.modem]
EnableFrameSkip = true
TargetBitrate =   600_000
MaxBitrate =    1_200_000
```
